[[redirects]]
  from = "/api/*"
  to = "http://43.200.176.59:8080/api/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "https"}

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
